### ISSUE TITLE
Browserland

### ISSUE THREAD

**Issue by samselikoff** [alex94puchades/jsonapify#1]
Great work on this package!

Any interest in publishing this as browser-consumable? I maintain an http mocking library and this is exactly what I need.

**Comment by alex94puchades** [comment]
Thanks! Yeah sure, I'm a little busy now trying to accomodate pagination and such into the whole thing, but tell me what you need and I'll work on it ASAP

**Comment by alex94puchades** [comment]
I've little experience on the front-end side, so I could be mistaken, but doesn't browserify automatically bundle CommonJS dependencies?

**Comment by samselikoff** [comment]
I think it does - when I get some time I'll experiment and report back on this :)

**Comment by samselikoff** [comment]
I'm going to close this for now, not sure it will make sense to use in my project just yet.

**Comment by alex94puchades** [comment]
Ok, remember if you miss some feature, just ask
