### ISSUE TITLE
Request query parameters

### ISSUE THREAD

**Issue by getlocalclout** [alex94puchades/jsonapify#10]
In the documentation you mention:

At this moment, selectors can get info from:
  Request params: jsonapify.param(...)
  Request query params: jsonapify.query(...)
  Resource parent object: jsonapify.parent(...)

I have been able to implement param/parent selector, but am having difficulty with the query string params. I have looked over your sample and don't see any use.

Tried many ways, but trying to do something along the lines of:

router.get("/",
	jsonapify.read("Info", {
		user: jsonapify.query('user')
	}),
	logger.logErrors(), jsonapify.errorHandler()
);

Where I would make a request like this:
localhost:3200/info?user=5708074dc203859baf2b40df

to the info route, and get the info associated with the user ID.

Any insight into this reported feature? I must be missing something...

Thanks!

**Comment by alex94puchades** [comment]
`router.get("/", [
    jsonapify.read("Info", {
        user: jsonapify.query('user')
    }),
    logger.logErrors(),
    jsonapify.errorHandler()
]);`

**Comment by alex94puchades** [comment]
Hi @getlocalclout, the `read` middleware takes as a second parameter a template of the query condition that will be passed to the mongoose model findOne method (see [here](https://github.com/alex94puchades/jsonapify/blob/master/lib/middleware/common.js#L54)). So if you're using mongoose default ID field, I think you should try with:

```js
router.get("/",
    jsonapify.read("Info", {
        _id: jsonapify.query('user')
    }),
    logger.logErrors(),
    jsonapify.errorHandler()
);
```

Also, make sure your first parameter is also correct (is your resource controller registered as "Info"?)

Hope it helps

**Comment by getlocalclout** [comment]
That answered my question. Thank you, and great work on this project!
