### ISSUE TITLE
Combining operations on single endpoint.

### ISSUE THREAD

**Issue by getlocalclout** [alex94puchades/jsonapify#11]
At a given endpoint, how would I go about combining for example enumerate/read operations. I want to be able to list/enumerate all items, but also use query parameters. Something like this:

```
router.get("/",
    jsonapify.enumerate('Info'),
    jsonapify.read([
        'Info', {
            _id: jsonapify.query('user')
        }
    ]),
    logger.logErrors(), jsonapify.errorHandler()
);
```

But that gives me an `Error: Can't set headers after they are sent.`

Thanks in advance!

**Comment by alex94puchades** [comment]
Hi @getlocalclout. In jsonapify, query parameters are available for all middleware (I can elaborate on that in case you need it). You should use the middleware that best matches your intent. In your example, it seems you want to select a single resource object of type "Info" based on the "user" query param, which is what the `read` middleware is for. On the other hand, the `enumerate` middleware is for returning a set of resource objects, matching or not a specific criteria. Why do you want the `enumerate` middleware here? Am I missing something?

**Comment by getlocalclout** [comment]
"query parameters are available for all middleware".. yes please elaborate. 

My thought, is that at any given endpoint/route, I should be able to list all the resource objects ('enumerate') or filter down by a query parameter. The above example might not be the best, as 'info' and 'user' is a one to one relationship. Let's say I had a 'posts' model/route. Sometimes I will want to query all the posts, and other times I want to query just the posts created by a particular user. That same endpoint should serve both purposes... Does this make more sense? 

Thank you.

**Comment by alex94cp** [comment]
> "query parameters are available for all middleware".. yes please elaborate.

[All](https://github.com/alex94puchades/jsonapify/blob/master/lib/middleware/enumerate.js#L19) [middleware](https://github.com/alex94puchades/jsonapify/blob/master/lib/middleware/read.js#L18) [take](https://github.com/alex94puchades/jsonapify/blob/master/lib/middleware/update.js#L14) [as](https://github.com/alex94puchades/jsonapify/blob/master/lib/middleware/modify.js#L14) [a](https://github.com/alex94puchades/jsonapify/blob/master/lib/middleware/assign.js#L14) [first](https://github.com/alex94puchades/jsonapify/blob/master/lib/middleware/remove.js#L13) argument a _chain_ that serves to locate the resource that will be the target of the request. This chain is then "resolved" to one or more resource objects, by using information from the [query](https://github.com/alex94puchades/jsonapify/blob/master/lib/selectors.js#L3), [param](https://github.com/alex94puchades/jsonapify/blob/master/lib/selectors.js#L9) and [parent resources](https://github.com/alex94puchades/jsonapify/blob/master/lib/selectors.js#L15) (these are called _selectors_). This is what I call **resource addressing** and it's explained [here](https://github.com/alex94puchades/jsonapify#middleware-and-resource-addressing). Beware that this feature is yet experimental and may have bugs.

> My thought, is that at any given endpoint/route, I should be able to list all the resource objects ('enumerate') or filter down by a query parameter. 

I think maybe [transaction filters](https://github.com/alex94puchades/jsonapify#transaction-filters), and more especifically the [filter](https://github.com/alex94puchades/jsonapify/blob/master/lib/filters/filter.js) _filter_ could serve that purpose. That way, you would use the _enumerate_ middleware only, and get back either all posts or all posts belonging to a specific user if a user-id was provided as query parameter. Is that what you are looking for?

**Note**: beware the more "RESTful" thing to do in this case would be to have two different end-points depending on the intent: a `/posts` and `/users/:user_id/posts`, but unfortunately relation middleware is not yet implemented in jsonapify (I'm sorry I can't devote as much time to this project as I'd like to).
