### ISSUE TITLE
Noob question, what's a model?

### ISSUE THREAD

**Issue by anlek** [alex94puchades/jsonapify#13]
Hey, in your docs, you keep loading a model but never show us what a `User` model looks like. I can't really figure out how to use this library without knowing what the model needs to look like (from which we would build the model resource like: `UserResource`)
Any more details would be great, thanks!

**Comment by alex94puchades** [comment]
@anlek @edmundo096 A Model is an object that defines the necessary operations for database retrieval/storage of resource objects. Currently, only mongoose models are supported, but I planned jsonapify to be backend agnostic somewhere in the future (maybe).

Regarding usage, do you find the information in the readme insufficient? What else would you like to see? As a workaround, you can always take a look at the [test](https://github.com/alex94puchades/jsonapify/tree/master/test) folder, though that's not an excuse for proper documentation, I know :sweat_smile:

**Comment by edmundo096** [comment]
@alex94puchades Indeed, looking at the test directory will help understanding the actual implementations and uses.
The Readme has a good introduction but for a quick-look search for "why I should use this library" or "how this library will help me", was not enough in my humble opinion.
I will take a look to this library a bit more in the future. Thanks for the reply!
