### ISSUE TITLE
Optional resource field handling [was: Requests throwing 500 Internal Server Error]

### ISSUE THREAD

**Issue by agraboso** [alex94puchades/jsonapify#4]
I have an Express router listening to requests to `/api/users`. Here's the module that exports that router.

``` js
const jsonapify = require('jsonapify');
const router = require('express').Router();

router.route('/')
  .get([
    jsonapify.enumerate('User'),
    jsonapify.errorHandler()
  ])
  .post([
    jsonapify.create('User'),
    jsonapify.errorHandler()
  ]);

router.route('/:username')
  .get([
    jsonapify.read([
      'User', { username: jsonapify.param('username') }
    ]),
    jsonapify.errorHandler()
  ])
  .patch([
    jsonapify.modify([
      'User', { username: jsonapify.param('username') }
    ]),
    jsonapify.errorHandler()
  ])
  .delete([
    jsonapify.remove([
      'User', { username: jsonapify.param('username') }
    ]),
    jsonapify.errorHandler()
  ]);

module.exports = router;
```

The resource definition is as follows.

``` js
module.exports = function (mongoose, jsonapify) {
  const resource = new jsonapify.Resource(mongoose.model('User'), {
    type: 'users',
    id: new jsonapify.Property('_id'),
    attributes: {
      username: new jsonapify.Property('username'),
      fullname: new jsonapify.Property('fullname'),
      displayFullname: new jsonapify.Property('displayFullname'),
      email: new jsonapify.Property('email'),
      password: {
        value: new jsonapify.Property('password'),
        readable: false
      },
      createdAt: new jsonapify.Property('createdAt'),
      modifiedAt: new jsonapify.Property('modifiedAt'),
      deleted: new jsonapify.Property('deleted'),
      permissions: new jsonapify.Property('permissions')
    },
    links: {
      self: new jsonapify.Template('/api/users/${username}')
    }
  });

  jsonapify.Registry.add('User', resource);

  return resource;
};
```

Say my database has a single user with username `test`. Then,
- A GET request to `/api/users` sends back a 200 OK with a list containing the single user, as expected.
- A GET request to `/api/users/test` sends back a 200 OK with the single user, as expected.
- A DELETE request to `/api/users/test` sends back a 204 No Content, as expected.

However,
- A GET request to `/api/users/nonexistent` results in a 500 Internal Server Error instead of the expected 404 Not Found. The stack trace is:

```
TypeError: Cannot read property 'toString' of undefined
  at ServerResponse.writeHead (_http_server.js:183:44)
  at ServerResponse.writeHead (/Users/agraboso/Code/c3902/node_modules/morgan/node_modules/on-headers/index.js:53:19)
  at ServerResponse.writeHead (/Users/agraboso/Code/c3902/node_modules/compression/node_modules/on-headers/index.js:53:19)
  at ServerResponse._implicitHeader (_http_server.js:150:8)
  at ServerResponse.res.end (/Users/agraboso/Code/c3902/node_modules/compression/index.js:94:14)
  at ServerResponse.send (/Users/agraboso/Code/c3902/node_modules/express/lib/response.js:204:10)
  at ServerResponse.json (/Users/agraboso/Code/c3902/node_modules/express/lib/response.js:249:15)
  at Response.send (/Users/agraboso/Code/c3902/node_modules/jsonapify/lib/Response.js:77:6)
  at middleware (/Users/agraboso/Code/c3902/node_modules/jsonapify/lib/middleware/errorHandler.js:14:12)
  at Layer.handle_error (/Users/agraboso/Code/c3902/node_modules/express/lib/router/layer.js:71:5)
  at next (/Users/agraboso/Code/c3902/node_modules/express/lib/router/route.js:129:13)
  at /Users/agraboso/Code/c3902/node_modules/jsonapify/lib/middleware/read.js:37:20
  at /Users/agraboso/Code/c3902/node_modules/jsonapify/node_modules/async/lib/async.js:52:16
  at /Users/agraboso/Code/c3902/node_modules/jsonapify/node_modules/async/lib/async.js:667:30
  at /Users/agraboso/Code/c3902/node_modules/jsonapify/node_modules/async/lib/async.js:173:37
  at /Users/agraboso/Code/c3902/node_modules/jsonapify/node_modules/async/lib/async.js:1166:30
```
- a DELETE request to `/api/users/nonexistent` results in a 500 Internal Server Error. The JSON API specification doesn't dictate what the response should be in this case, but I'd expect a 404 Not Found. Here is the stack trace:

```
TypeError: Cannot read property 'toString' of undefined
  at ServerResponse.writeHead (_http_server.js:183:44)
  at ServerResponse.writeHead (/Users/agraboso/Code/c3902/node_modules/morgan/node_modules/on-headers/index.js:53:19)
  at ServerResponse.writeHead (/Users/agraboso/Code/c3902/node_modules/compression/node_modules/on-headers/index.js:53:19)
  at ServerResponse._implicitHeader (_http_server.js:150:8)
  at ServerResponse.res.end (/Users/agraboso/Code/c3902/node_modules/compression/index.js:94:14)
  at ServerResponse.send (/Users/agraboso/Code/c3902/node_modules/express/lib/response.js:204:10)
  at ServerResponse.json (/Users/agraboso/Code/c3902/node_modules/express/lib/response.js:249:15)
  at Response.send (/Users/agraboso/Code/c3902/node_modules/jsonapify/lib/Response.js:77:6)
  at middleware (/Users/agraboso/Code/c3902/node_modules/jsonapify/lib/middleware/errorHandler.js:14:12)
  at Layer.handle_error (/Users/agraboso/Code/c3902/node_modules/express/lib/router/layer.js:71:5)
  at next (/Users/agraboso/Code/c3902/node_modules/express/lib/router/route.js:129:13)
  at /Users/agraboso/Code/c3902/node_modules/jsonapify/lib/middleware/remove.js:22:20
  at /Users/agraboso/Code/c3902/node_modules/jsonapify/node_modules/async/lib/async.js:382:13
  at /Users/agraboso/Code/c3902/node_modules/jsonapify/node_modules/async/lib/async.js:52:16
  at /Users/agraboso/Code/c3902/node_modules/jsonapify/node_modules/async/lib/async.js:267:21
  at /Users/agraboso/Code/c3902/node_modules/jsonapify/node_modules/async/lib/async.js:44:16
```
- a POST request to `/api/users` with body

``` js
{
  "data": {
    "type": "users",
    "attributes": {
      "username": "anothertest",
      "fullname": "Another Test",
      "displayFullname": false,
      "email": "test2@example.com",
      "createdAt": "2015-09-06T16:22:24.470Z",
      "modifiedAt": "2015-09-06T16:22:24.470Z",
      "deleted": false,
      "permissions": [
        "self",
        "moderate",
        "admin"
      ]
    }
  }
}
```

also results in a 500 Internal Server Error with the following stack trace:

```
TypeError: Cannot read property 'toString' of undefined
  at ServerResponse.writeHead (_http_server.js:183:44)
  at ServerResponse.writeHead (/Users/agraboso/Code/c3902/node_modules/morgan/node_modules/on-headers/index.js:53:19)
  at ServerResponse.writeHead (/Users/agraboso/Code/c3902/node_modules/compression/node_modules/on-headers/index.js:53:19)
  at ServerResponse._implicitHeader (_http_server.js:150:8)
  at ServerResponse.res.end (/Users/agraboso/Code/c3902/node_modules/compression/index.js:94:14)
  at ServerResponse.send (/Users/agraboso/Code/c3902/node_modules/express/lib/response.js:204:10)
  at ServerResponse.json (/Users/agraboso/Code/c3902/node_modules/express/lib/response.js:249:15)
  at Response.send (/Users/agraboso/Code/c3902/node_modules/jsonapify/lib/Response.js:77:6)
  at middleware (/Users/agraboso/Code/c3902/node_modules/jsonapify/lib/middleware/errorHandler.js:14:12)
  at Layer.handle_error (/Users/agraboso/Code/c3902/node_modules/express/lib/router/layer.js:71:5)
  at next (/Users/agraboso/Code/c3902/node_modules/express/lib/router/route.js:129:13)
  at /Users/agraboso/Code/c3902/node_modules/jsonapify/lib/middleware/create.js:37:20
  at /Users/agraboso/Code/c3902/node_modules/jsonapify/node_modules/async/lib/async.js:52:16
  at Immediate._onImmediate (/Users/agraboso/Code/c3902/node_modules/jsonapify/node_modules/async/lib/async.js:1163:34)
  at processImmediate [as _immediateCallback] (timers.js:371:17)
```

I don't know whether it is me doing something wrong or jsonapify. I've tried to parse the code, but it is difficult to follow and completely undocumented. Can you help?

**Comment by alex94puchades** [comment]
Thanks for the report. Yep, there's a ResourceNotFound error being passed to the errorHandler middleware, which should translate it to the more appropiate 404 http status, but an exception is being thrown from within Response#send at line 75. I'll take a look.

**Comment by alex94puchades** [comment]
v1.5.10 has been released which fixes this issue. Unit tests will be added soon.

**Comment by agraboso** [comment]
@alex94puchades Thanks for a very speedy fix. I can confirm GET and DELETE requests to nonexistent records now correctly return 404 Not Found.

I still cannot make POST requests work though. Trying the one in my post above results in a 422 Unprocessable Entity with the following body
```js
{
  "errors": [
    {
      "detail": "Invalid Field Value"
    }
  ],
  "jsonapi": {
    "version": "1.0"
  }
}
```
After some tinkering, I've realized two things:

1. The body of my requests was not being parsed, because I called the `body-parser` middleware as `app.use(bodyParser.json())`. The correct way is `app.use(bodyParser.json({ type: 'application/vnd.api+json' }))`. It might be advisable to remark on this in the documentation of `jsonapify`.
2. After correcting the above, I still get a 422 Unprocessable Entity. The invalid field value turns out to be the `id` field. But POST requests without an `id` field should be accepted by the server!

**Comment by alex94puchades** [comment]
Regarding `body-parser`, I agree it should be made more clear in the documentation. In addition, I'll try to make `body-parser` use some heuristics to handle this so that special settings are not needed (I hope it gets accepted).

Now with the `id` field, if I understand correctly, you are asking the id field to have the same semantics as a constant (that is, throw an error if request field does not match the one at resource descriptor) but instead of from the resource descriptor, the matching field should be retrieved from the resource object, retrieved from the URI params only. That is a little tricky to make in a generic way.

The best way to deal around it would be to make the `id` field not writable. Would that work for you?

**Comment by agraboso** [comment]
> Now with the `id` field, if I understand correctly, you are asking the id field to be optional and, in case it does appear (think of a READ action), you're asking it to have the same semantics as a constant (that is, throw an error if request field does not match the one at resource descriptor) but instead of from the resource descriptor, the id field should match params from the uri. That is a little tricky to make in a generic way.

I'm sorry, but I don't understand what you mean.

> The best way to deal around it that I can think of would be to make the `id` field not writable. Would that work for you?

Making `id` not `writable` does provide a workaround, but it precludes a server using `jsonapify` from accepting client-generated IDs &mdash; which is a use case considered in the JSON API specification.

There is also another thing that bothers me a bit: optional fields must be marked `nullable`. This is exactly the opposite to how `mongoose` does things &mdash; you must mark the *required* fields. So, for example, to be able to omit the `createdAt` and `modifiedAt` fields in my example POST request above, I would need to declare them as `nullable` properties. But I really should not be sending those fields, but rather leaving it to `mongoose` to use a `default` to set them on the database document upon creation.

I think dropping `nullable` altogether (along with checks for `undefined` such as those in lines 38 and 46 of `lib/Field.js`) would work better:

1. `id` would not need to be declared as not `writable`. If an `id` is not present in a POST request, the MongoDB server would take care of creating one. If an `id` is indeed present, it would be the job of the `mongoose` validator to decide whether it should be accepted or not, and how (accepting it; dropping it and replacing it with the MongoDB server generated one; or throwing an error).
2. Properties that are optional for whatever reason (they are not marked as `required` in the `mongoose` model, or have a `default`) would not need to be marked `nullable`.

In my mind, `writable` and `readable` are perfectly natural and have a very clear purpose, but `nullable` is not (and the use case above of making the field optional does not correspond with the meaning of the word). But I don't know what use cases you had in mind when you included `nullable` fields...

I'm going to try to write an implementation of the above and see how it works. If it does, I'll make a PR and let you decide.

**Comment by alex94puchades** [comment]
>
Making id not writable does provide a workaround, but it precludes a server using jsonapify from accepting client-generated IDs — which is a use case considered in the JSON API specification.
>

Client-generated IDs are supported by jsonapify by means of the ASSIGN action. Whether the id field can be set by the user or not should be configured on a per-resource basis. And that's the point of the id field being readable or writable.

So, just to clarify the current situation. In jsonapify parlance there are two kind of actions: **query** and **modify** actions. Query actions are *READ* and *ENUM*. Modify actions are *UPDATE* and *ASSIGN* (MODIFY is an specific case). Making a field *readable* exposes it to query actions. Making it *writable* makes it susceptible to modify actions, and so required in modify requests (aka POST/PUT requests). The point of *nullable* is to allow a field to appear or not in query AND modify requests. So you are right that nullable does not have the semantic meaning of readable or writable, but it does fill an use case, exactly the one you said:
>\[...\] leaving it to mongoose to use a default to set them on the database document upon creation

In addition to that, nullable makes it easier to add fields in a backward-compatible way (without  the need of a major API version change).

>
Properties that are optional for whatever reason (they are not marked as required in the mongoose model, or have a default) would not need to be marked nullable.
>

I really see your point, but think about it: jsonapify can be used by a lot of different people. There are people that may want your behaviour (all fields optional by default), while others may want fields to be implicitly required but explicitly marked as optional. Mongoose does the former while I very much prefer the later. So I'd very much leave nullable as it is currently.

What I could see being incorporated to jsonapify would be user-defined global defaults: maybe a Runtime object which, in addition to type (de)registration, also handles project-wide field defaults.

**Comment by agraboso** [comment]
> > Making id not writable does provide a workaround, but it precludes a server using jsonapify from accepting client-generated IDs — which is a use case considered in the JSON API specification.

> Client-generated IDs are supported by jsonapify by means of the ASSIGN action. Whether the id field can be set by the user or not should be configured on a per-resource basis. And that's the point of the id field being readable or writable.

I don't see how client-generated IDs are supported by `assign`. Can you explain?

Let me tell you how I see the logic of POST requests regarding `id` with and without #5.

1. Without #5:
  1. You can have (in fact, force) client-generated IDs by declaring `id`  as `writable: true, nullable: false`.
  2. You can have (in fact, force) server-generated IDs by declaring  `id`  as `writable: false, nullable: true`.
  3. Declaring  `id`  as `writable: false, nullable: false` is a strange combination in which you must supply an `id` in POST requests, and it is promptly ignored.
  4. Declaring `id` as `writable: true, nullable: true` seems like it should allow you to use client-generated IDs, but default to server-generated ones in case `id` is missing from a POST request. But it doesn't do that: MongoDB responds with an error saying you need an `_id` field. In order to solve this, validation would has to be added to the `mongoose` model to check whether the `id` attribute of a creation request is `undefined` and then delete it.
2. With #5,
  1. You can have client-generated IDs by declaring `id`  as `writable: true`. If you don't provide an `id` in a POST request, it is then up to `mongoose` to decide whether to throw a validation error (that is, force client-generated IDs) or to let the request go through to the MongoDB server, which would then generate an ID itself without any need for validation.
  2. You can have (in fact, force) server-generated IDs by declaring `id`  as `writable: false`.

The situation in 1.iv / 2.i above also presents when there are other properties that I would like to give users the option of specifying, but if they don't I'll do programatically.

> In addition to that, nullable makes it easier to add fields in a backward-compatible way (without the need of a major API version change).

You mean you would add new fields with `nullable: true`, right? With #5, you don't even need that: just add the new field to the resource definition! 

> I really see your point, but think about it: jsonapify can be used by a lot of different people. There are people that may want your behaviour (all fields optional by default), while others may want fields to be implicitly required but explicitly marked as optional. Mongoose does the former while I very much prefer the later. So I'd very much leave nullable as it is currently.

I understand your preference, but I disagree with it. One reason is what I explained above &mdash; which ties in very strongly with the fact that you are doing things the opposite way `mongoose` does. The other is that the way I see `jsonapify` is as a bridge between `mongoose` and the public API of the server. You're trying to force just a tiny bit of validation in `jsonapify`, while leaving the rest to `mongoose` &mdash; and, as I said in 1.iv above, the separation between those types of validation is not even clear-cut. I think it is more natural, more flexible and, most importantly, more maintainable to put all validation in one place.

> What I could see being incorporated to jsonapify would be user-defined global defaults: maybe a Runtime object which, in addition to type (de)registration, also handles project-wide field defaults.

I rather like this idea. You could have your fields required, I could have mine optional. In fact, after I submitted #3, I realized that it would have been more elegant to make the whole of `jsonapify` into a singleton, instead of just the registry: the `_resources` object in the registry could then be owned by `jsonapify` itself. A global options object would be trivial to add too.

I would also rename `nullable` into something like `required` &mdash; a more semantic name &mdash;, so you would prefer the global default `required: true` (effectively working without #5) and I would use `required: false` (effectively working with #5).

I'll try to put a PR together some time this week.

**Comment by alex94puchades** [comment]
Hi @agraboso, sorry for the delay:

>>>Making id not writable does provide a workaround, but it precludes a server using jsonapify from accepting client-generated IDs — which is a use case considered in the JSON API specification.
>
>>Client-generated IDs are supported by jsonapify by means of the ASSIGN action. Whether the id field can be set by the user or not should be configured on a per-resource basis. And that's the point of the id field being readable or writable.
>
>I don't see how client-generated IDs are supported by assign. Can you explain?

Now I realize I wasn't clear at all. My line of reasoning was this: *ASSIGN* performs an if-not-exist-then-create-else-update operation, which usually maps to a PUT request in REST terms. When used for resource creation, PUT requests include a client-generated ID. But you are correct that both *ASSIGN* and *CREATE* could theoretically used for client-generated IDs, and for that both do require a writable id field.

>You mean you would add new fields with nullable: true, right? With #5, you don't even need that: just add the new field to the resource definition! 

Correct.

>I understand your preference, but I disagree with it. One reason is what I explained above — which ties in very strongly with the fact that you are doing things the opposite way mongoose does. The other is that the way I see jsonapify is as a bridge between mongoose and the public API of the server. You're trying to force just a tiny bit of validation in jsonapify, while leaving the rest to mongoose — and, as I said in 1.iv above, the separation between those types of validation is not even clear-cut. I think it is more natural, more flexible and, most importantly, more maintainable to put all validation in one place.

That's why, the more I think about it, the more I dislike nullable. However, there are still some concerns with respect to optional being the default. The one I find more worrying is related to json-api conformance: I could be wrong but I think #5 would make it impossible to enforce the difference between an *UPDATE* operation and a *MODIFY* one (at least without the addition of a required field modifier, which completely defeats the purpose of #5).

One of the golden rules of jsonapify is that we offer the building blocks to build a compliant JSON API. Developers are free to deviate from the standard where they see fit, but we cannot enforce that. As an example, the JSON-API mandates the UPDATE operation to map to PATCH requests. I personally think developers would find it surprising, and I routinely [use PUT for that](https://github.com/avem-ifmsa/avem-rest-api/blob/master/src/app/controllers/clients.js). But we cannot in any way enforce that from within jsonapify or otherwise we'd risk losing all users looking for a standard-compliant [implementation](http://jsonapi.org/implementations/).

>Declaring id as writable: true, nullable: true seems like it should allow you to use client-generated IDs, but default to server-generated ones in case id is missing from a POST request. But it doesn't do that: MongoDB responds with an error saying you need an _id field.

Yep, it certainly does not make much sense. The current behaviour is confusing. I think we should get rid of nullable for the next major release. We could support optional fields via a user-defined global setting. That would require special handling of the id field in the middleware. There may be other ways, so I think this requires more discussion. For now, as a workaround, I think we should go for user-defined global defaults.

**Comment by alex94puchades** [comment]
> Yep, currently in that case ~~writable prevails, which makes the id field mandatory for modify actions, which defeats the purpose of nullable~~. I think we should make writable fields mandatory in modify requests by default (because of jsonapi conformance), optional if nullable (because of 1.iv) and go for user-defined global defaults for now.

I can confirm jsonapify behaves as expected. See [code sample](http://pastebin.com/fpdP0bYP).

> iv. Declaring id as `writable: true, nullable: true` seems like it should allow you to use client-generated IDs, but default to server-generated ones in case id is missing from a POST request. But it doesn't do that: MongoDB responds with an error saying you need an _id field.

Currently, jsonapify handles the id field like any other field, so atm resources may have either client or server-generated IDs, independently of *nullable* being set or not. For that we would need special handling of the id field. Do you need that or it was only to make a point?

**Comment by agraboso** [comment]
@alex94puchades: the hard drive on my laptop died a couple of days ago, so I have very limited possibility of looking at these things. I'll get back to you as soon as I have it back.

**Comment by alex94puchades** [comment]
@agraboso: I'm sorry to hear that, your contributions are always very useful
