### ISSUE TITLE
Is it possible to use jsonapify with sequelizejs?

### ISSUE THREAD

**Issue by funnyprinter** [alex94puchades/jsonapify#6]
Is it possible to use jsonapify with sequelizejs as mysql orm?

**Comment by alex94puchades** [comment]
Not at this moment. Only mongoose is supported for now. Support for multiple backends is planned for the next major version though.

**Comment by funnyprinter** [comment]
When is the next major release planned? Are you working on it already? Do
you know any jsonapi lib for node working with MySQL? Or any other orm
working with MySQL and the lib?

Alejandro Caravaca Puchades <notifications@github.com> schrieb am Mo., 21.
Sep. 2015 01:40:

**Comment by alex94puchades** [comment]
>When is the next major release planned? Are you working on it already?

I'm sorry but not in the near future.

>Do you know any jsonapi lib for node working with MySQL? Or any other orm working with MySQL and the lib?

Have you checked out [jsonapi.org](http://jsonapi.org/implementations/#server-libraries-node-js)?
